name: TagBot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  TagBot:
    uses: "ITensor/ITensorActions/.github/workflows/TagBot.yml@main"
    with:
      localregistry: https://github.com/ITensor/ITensorRegistry.git
    secrets:
      TAGBOT_TOKEN: ${{ secrets.TAGBOT_TOKEN }}
